name: check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

env:
  JDK_DISTRIBUTION: 'temurin'
  JDK_VERSION: '21'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        lint-tool: [ test, detekt, ktlintCheck ]

    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run lint
        run: ./gradlew ${{ matrix.lint-tool }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: ./**/build/reports
